GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRpZWdvIiwiaWF0IjoxNzE5ODE4NjIxLCJleHAiOjE3MTk4MTk4MjF9.cmxl1x7JfkemtCo9fUyVpTV7NBnKZgiHMH1E_hiPb7U

###

DELETE http://localhost:3000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRpZWdvIiwiaWF0IjoxNzE5ODE4NjAzfQ.I6H8ie6U6FP8R_PamL1EMKpwy76TAvDhm3WjpViRlGE"
}

###

POST http://localhost:3000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRpZWdvIiwiaWF0IjoxNzE5ODE4NjAzfQ.I6H8ie6U6FP8R_PamL1EMKpwy76TAvDhm3WjpViRlGE"
}


###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "diego",
    "password": "123"
}